# Generated by Django 4.2 on 2023-04-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_details',
            name='img',
            field=models.ImageField(default='sdnk', upload_to='Gallery'),
            preserve_default=False,
        ),
    ]
